// Auto-generated file - DO NOT EDIT
// Generated by @ai-toolkit/utils generate-index
// To regenerate, run: npx nx run @ai-toolkit/skills-agnostic:generate-index

// Skill types - compatible with Claude Code plugin system
type SkillName = 'codebase-exploration';

export type Skills = {
  [key in SkillName]: {
    description: string;
    filePath: string;
  };
};

// Export skills with descriptions and file paths
export const skills: Skills = {
  'codebase-exploration': {
    description:
      'Use this skill when exploring or analyzing a codebase structure, understanding architecture, or mapping out dependencies between components.',
    filePath: './codebase-exploration.md',
  },
} as const;

export type { SkillName };
