// Auto-generated file - DO NOT EDIT
// Generated by @ai-toolkit/utils generate-skill-index
// To regenerate, run: npx nx run @ai-toolkit/skills-agnostic:generate-index

// Skill types
type SkillName = 'jupyter-notebook' | 'pdf' | 'xlsx';

export type Skills = {
  [key in SkillName]: {
    description: string;
    directoryPath: string;
  };
};

// Export skills with descriptions and directory paths
export const skills: Skills = {
  'jupyter-notebook': {
    description:
      'Work with Jupyter notebooks, understanding code cells, markdown documentation, and outputs for data science and analysis workflows',
    directoryPath: './jupyter-notebook',
  },
  pdf: {
    description:
      'Read and analyze PDF documents, extracting text content, structure, and metadata for comprehensive document understanding',
    directoryPath: './pdf',
  },
  xlsx: {
    description:
      'Work with Excel spreadsheet files, analyzing data, understanding formulas, and extracting structured information from worksheets',
    directoryPath: './xlsx',
  },
} as const;

export type { SkillName };
