# zizmor configuration for GitHub Actions security linting
# https://docs.zizmor.sh/configuration/
#
# All findings are addressed via:
# 1. Code fixes (template injection → env vars, excessive-permissions → per-job blocks)
# 2. Inline comments (# zizmor: ignore[artipacked]) for justified persist-credentials usage
#
# Run: zizmor .github/workflows/
# Expected result: 0 findings
#
# Justified artipacked suppressions (inline comments):
# - 3 checkout steps that need persist-credentials for git push operations
# - Each is annotated with: # zizmor: ignore[artipacked] — <reason>
# - Risk mitigated by least-privilege per-job permissions and Bullfrog scanning

rules: {}
