// Auto-generated file - DO NOT EDIT
// Generated by @ai-toolkit/utils generate-index
// To regenerate, run: bunx nx run @ai-toolkit/agents-agnostic:generate-index

// Agent types
type Agent =
  | 'agent-capability-analyst'
  | 'agent-orchestrator'
  | 'code-explainer'
  | 'context-loader'
  | 'debug-assistant'
  | 'doc-writer'
  | 'plan-reviewer'
  | 'planner'
  | 'refactorer'
  | 'researcher'
  | 'style-enforcer'
  | 'test-writer';

type Agents = {
  [key in Agent]: {
    description: string;
    filePath: string;
  };
};

// Export agents with descriptions and file paths
export const agents: Agents = {
  'agent-capability-analyst': {
    description:
      'Specialist in analyzing AI agent capabilities and matching them to software development tasks through semantic understanding and competency extraction',
    filePath: './agent-capability-analyst.md',
  },
  'agent-orchestrator': {
    description:
      'Intelligent orchestrator that coordinates other AI agents for complex software development workflows, matching tasks to specialists based on capabilities',
    filePath: './agent-orchestrator.md',
  },
  'code-explainer': {
    description:
      'Explain code purpose, behavior, dependencies, and potential risks in clear developer language.',
    filePath: './code-explainer.md',
  },
  'context-loader': {
    description:
      'Deep dive into codebase areas to build comprehensive understanding before implementation work.',
    filePath: './context-loader.md',
  },
  'debug-assistant': {
    description:
      'Diagnose errors from logs or failing tests and propose fixes.',
    filePath: './debug-assistant.md',
  },
  'doc-writer': {
    description:
      'Generate developer-facing documentation from code or changes.',
    filePath: './doc-writer.md',
  },
  'plan-reviewer': {
    description:
      'Critically analyze implementation plans for completeness, feasibility, and alignment with codebase patterns',
    filePath: './plan-reviewer.md',
  },
  planner: {
    description: 'Create detailed implementation plans without writing code',
    filePath: './planner.md',
  },
  refactorer: {
    description:
      'Propose safe, incremental refactors with small patch hunks and clear rationale.',
    filePath: './refactorer.md',
  },
  researcher: {
    description:
      'Conduct comprehensive research by combining web documentation with codebase analysis.',
    filePath: './researcher.md',
  },
  'style-enforcer': {
    description:
      'Identify style and convention issues and propose idiomatic fixes.',
    filePath: './style-enforcer.md',
  },
  'test-writer': {
    description:
      'Generate or extend deterministic tests for target code with clear rationale and edge-case coverage.',
    filePath: './test-writer.md',
  },
} as const;

export type AgentName = keyof typeof agents;
