// Auto-generated file - DO NOT EDIT
// Generated by @ai-toolkit/utils generate-index
// To regenerate, run: bunx nx run @ai-toolkit/commands-agnostic:generate-index

type CommandName =
  | 'create-pr'
  | 'deploy'
  | 'explain-file'
  | 'fix-bug'
  | 'gen-tests'
  | 'implement-spec'
  | 'monitor'
  | 'plan'
  | 'refactor'
  | 'research'
  | 'review-code'
  | 'review-plan'
  | 'review-pr'
  | 'understand-area';

export type Commands = {
  [key in CommandName]: {
    description: string;
    filePath: string;
  };
};

export const commands: Commands = {
  'create-pr': {
    description:
      'Create or update a Graphite PR with auto-generated conventional commit messages and comprehensive descriptions based on code diffs.',
    filePath: './create-pr.md',
  },
  deploy: {
    description:
      'Orchestrate deployment pipelines, infrastructure setup, and CI/CD configuration using specialized deployment agents.',
    filePath: './deploy.md',
  },
  'explain-file': {
    description:
      'Comprehensive code explanation using multi-agent analysis for architecture, patterns, security, and performance insights.',
    filePath: './explain-file.md',
  },
  'fix-bug': {
    description:
      'Comprehensively diagnose bugs with root cause analysis, systematic fixes, regression tests, and prevention strategies.',
    filePath: './fix-bug.md',
  },
  'gen-tests': {
    description:
      'Generate comprehensive tests with advanced testing strategies, scenario generation, and edge case identification using the enhanced test-writer agent.',
    filePath: './gen-tests.md',
  },
  'implement-spec': {
    description:
      'Orchestrate implementation of spec-workflow tasks using intelligent agent coordination, parallel execution, and quality gates.',
    filePath: './implement-spec.md',
  },
  monitor: {
    description:
      'Set up comprehensive monitoring for applications with automated metrics identification, alerting, and dashboard configuration',
    filePath: './monitor.md',
  },
  plan: {
    description:
      'Create a comprehensive implementation plan with hierarchical task decomposition, agent orchestration, and risk assessment for any task, feature, refactor, or architectural change',
    filePath: './plan.md',
  },
  refactor: {
    description:
      'Orchestrate comprehensive refactoring with architectural analysis, pattern application, and incremental safety checks.',
    filePath: './refactor.md',
  },
  research: {
    description:
      'Research a topic by combining web search with codebase analysis for comprehensive understanding.',
    filePath: './research.md',
  },
  'review-code': {
    description:
      'Comprehensive code review using multiple specialized agents for architecture, security, performance, and style analysis.',
    filePath: './review-code.md',
  },
  'review-plan': {
    description:
      'Critically review an implementation plan for completeness, feasibility, and alignment with codebase patterns',
    filePath: './review-plan.md',
  },
  'review-pr': {
    description:
      'Orchestrate comprehensive pull request review using specialized agents for architecture, security, performance, testing, and maintainability analysis.',
    filePath: './review-pr.md',
  },
  'understand-area': {
    description:
      'Deep dive into a codebase area to build comprehensive understanding before implementation.',
    filePath: './understand-area.md',
  },
} as const;
