// Auto-generated file - DO NOT EDIT
// Generated by @ai-toolkit/utils generate-index
// To regenerate, run: bunx nx run @ai-toolkit/commands-agnostic:generate-index

type CommandName =
  | 'explain-file'
  | 'fix-bug'
  | 'gen-tests'
  | 'plan'
  | 'plan-feature'
  | 'refactor'
  | 'research'
  | 'review-plan'
  | 'review-pr'
  | 'understand-area';

export type Commands = {
  [key in CommandName]: {
    description: string;
    filePath: string;
  };
};

export const commands: Commands = {
  'explain-file': {
    description:
      'Explain a file or module in plain English with responsibilities, invariants, and risks.',
    filePath: './explain-file.md',
  },
  'fix-bug': {
    description:
      'Diagnose an error message or failing test and propose a smallest-possible fix with an optional regression test.',
    filePath: './fix-bug.md',
  },
  'gen-tests': {
    description:
      'Generate or extend tests for one or more files using the test-writer subagent.',
    filePath: './gen-tests.md',
  },
  plan: {
    description:
      'Create a detailed implementation plan for a task without writing code',
    filePath: './plan.md',
  },
  'plan-feature': {
    description:
      'Turn a natural-language feature idea into a concrete implementation plan with tasks and file-level changes.',
    filePath: './plan-feature.md',
  },
  refactor: {
    description:
      'Suggest and return minimal, safe refactors for a file or path.',
    filePath: './refactor.md',
  },
  research: {
    description:
      'Research a topic by combining web search with codebase analysis for comprehensive understanding.',
    filePath: './research.md',
  },
  'review-plan': {
    description:
      'Critically review an implementation plan for completeness, feasibility, and alignment with codebase patterns',
    filePath: './review-plan.md',
  },
  'review-pr': {
    description:
      'Review the current changes or a specified branch/commit-range. Summarize risks and suggest improvements.',
    filePath: './review-pr.md',
  },
  'understand-area': {
    description:
      'Deep dive into a codebase area to build comprehensive understanding before implementation.',
    filePath: './understand-area.md',
  },
} as const;
