// Auto-generated file - DO NOT EDIT
// Generated by @ai-toolkit/claude-skills generate script
// To regenerate, run: npx nx run @ai-toolkit/claude-skills:generate-index

type SkillName =
  | 'claude-docs-updater'
  | 'code-refactorer'
  | 'codebase-explorer'
  | 'graphite-stack-updater'
  | 'implementation-planner'
  | 'plan-executor'
  | 'plan-reviewer'
  | 'plan-swarm'
  | 'pr-creator'
  | 'pr-issue-resolver'
  | 'pr-reviewer'
  | 'prompt-optimizer'
  | 'tech-debt-analyzer'
  | 'topic-researcher';

export interface SkillDefinition {
  description: string;
  dirPath: string;
  files: string[];
  allowedTools?: string;
  model?: string;
}

export type Skills = {
  [key in SkillName]: SkillDefinition;
};

export const skills: Skills = {
  'claude-docs-updater': {
    description:
      'Intelligently update CLAUDE.md files based on code changes. Use PROACTIVELY after making significant code changes, when user mentions updating documentation, or when staged changes should be reflected in CLAUDE.md. Triggers: "update claude.md", "update documentation", "sync docs", "document changes", "update the docs", "reflect changes in docs", "keep docs updated".',
    dirPath: './claude-docs-updater',
    files: ['SKILL.md'],
    allowedTools: 'Read, Write, Edit, Bash(git diff:*), Bash(git status:*), Glob',
  },
  'code-refactorer': {
    description:
      'Orchestrate comprehensive code refactoring with architectural analysis, pattern application, and incremental safety checks. Use PROACTIVELY and AUTOMATICALLY when user wants to refactor code, improve code quality, reduce complexity, apply design patterns, or clean up technical debt. Triggers: "refactor", "clean up", "improve", "simplify", "reduce complexity", "apply pattern", "restructure", "reorganize", "technical debt", "code smell", "extract", "inline".',
    dirPath: './code-refactorer',
    files: ['SKILL.md'],
    allowedTools:
      'Read, Grep, Bash(git diff:*), Bash(git show:*), Task(subagent_type:refactorer), Task(subagent_type:style-enforcer), Task(subagent_type:code-explainer), Task(subagent_type:test-writer), Task(subagent_type:agent-orchestrator)',
  },
  'codebase-explorer': {
    description:
      'Deep codebase exploration and understanding. Use PROACTIVELY and AUTOMATICALLY when user asks how something works, wants to understand code, asks about architecture, needs to find where something is implemented, or before planning any feature. Triggers: "how does", "where is", "understand", "find", "explain", "architecture", "implementation", "show me", "what does", "trace", "follow", "dig into", "explore".',
    dirPath: './codebase-explorer',
    files: ['SKILL.md', 'exploration-guide.md'],
    allowedTools:
      'Bash(git ls-files:*), Bash(find:*), Bash(git log:*), Bash(git show:*), Bash(npx nx graph:*), Glob, Grep, Read, WebFetch, Task(subagent_type:context-loader)',
  },
  'graphite-stack-updater': {
    description:
      'Automate Graphite PR stack updates by resolving review comments and syncing all affected PRs. Use when user has a Graphite stack with comments to address, needs to update multiple PRs, or wants to sync stack after changes. Triggers: "update the stack", "address stack comments", "sync graphite", "gt stack update", "update upstack", "resolve PR comments", "graphite sync".',
    dirPath: './graphite-stack-updater',
    files: ['SKILL.md'],
    allowedTools:
      'Bash(gt:*), Bash(gh:*), Bash(git:*), Read, Write, Edit, Task(subagent_type:graphite-stack-updater), Task(subagent_type:code-reviewer)',
  },
  'implementation-planner': {
    description:
      'Create actionable implementation plans through multi-agent collaborative refinement. Use PROACTIVELY and AUTOMATICALLY when user wants to implement a feature, add functionality, refactor code, fix complex bugs, or make architectural changes. Triggers: "implement", "add", "build", "create", "develop", "refactor", "migrate", "design", "architect", "plan", "feature", "how should I", "what\'s the best way to".',
    dirPath: './implementation-planner',
    files: ['SKILL.md', 'planning-guide.md'],
    allowedTools:
      'Read, Glob, Grep, LS, Task, WebSearch, WebFetch, Write(*.md), Bash(git ls-files:*), Bash(mkdir:*)',
    model: 'claude-sonnet-4-5-20250929',
  },
  'plan-executor': {
    description:
      'Execute implementation plans step-by-step with progress tracking and optional test/doc generation. Use AUTOMATICALLY when user wants to execute a plan, implement a planned feature, or has an approved plan ready. Triggers: "execute", "implement the plan", "run the plan", "start implementing", "let\'s build", "go ahead", "proceed with", "start the implementation", "follow the plan".',
    dirPath: './plan-executor',
    files: ['SKILL.md', 'execution-guide.md'],
    allowedTools:
      'Read, Write, Edit, Glob, Grep, Bash, Task(subagent_type:test-writer), Task(subagent_type:doc-writer)',
  },
  'plan-reviewer': {
    description:
      'Critically review implementation plans for completeness, feasibility, and alignment with codebase patterns. Use PROACTIVELY and AUTOMATICALLY when user has a plan to review, wants feedback on an implementation strategy, or needs validation before executing. Triggers: "review the plan", "check the plan", "is this plan good", "validate plan", "feedback on plan", "before we execute", "does this look right".',
    dirPath: './plan-reviewer',
    files: ['SKILL.md'],
    allowedTools: 'Read, Glob, Grep, LS, WebSearch, WebFetch, Task(subagent_type:plan-reviewer)',
  },
  'plan-swarm': {
    description:
      'Collaboratively refine plans through multi-agent discussion and consensus-building. Use when user wants multiple perspectives on a plan, needs expert opinions, or wants to improve a strategy through collaborative refinement. Triggers: "get feedback from experts", "multiple perspectives", "collaborative review", "swarm", "expert opinions", "refine the plan", "discuss the approach".',
    dirPath: './plan-swarm',
    files: ['SKILL.md'],
    allowedTools: 'Read, Glob, Grep, Task, WebSearch, WebFetch',
    model: 'claude-sonnet-4-5-20250929',
  },
  'pr-creator': {
    description:
      'Create or update Graphite PRs with auto-generated conventional commit messages and comprehensive descriptions. Use PROACTIVELY when user wants to create a PR, push changes for review, or submit work. Triggers: "create PR", "make a PR", "submit PR", "push for review", "open PR", "create pull request", "gt submit", "ready for review".',
    dirPath: './pr-creator',
    files: ['SKILL.md'],
    allowedTools:
      'Bash(git:*), Bash(gt:*), Bash(gh:*), Read, Glob, Grep, Task(subagent_type:pr-creator), Task(subagent_type:commit-message-generator)',
  },
  'pr-issue-resolver': {
    description:
      'Review GitHub PRs, address review comments, and fix CI/CD failures to make PRs merge-ready. Use PROACTIVELY and AUTOMATICALLY when user mentions PR review comments, CI failures, failing checks, needs to fix a PR, or wants to address feedback on a pull request. Triggers: "PR", "pull request", "review comments", "CI failing", "checks failing", "fix the PR", "address comments", "address feedback", "merge blocked", "pipeline failed", "build failing", "tests failing on PR".',
    dirPath: './pr-issue-resolver',
    files: ['SKILL.md', 'pr-guide.md'],
    allowedTools:
      'Bash, Read, Write, Edit, Grep, Glob, WebFetch, WebSearch, Task, mcp__github__pull_request_read, mcp__github__get_file_contents, mcp__github__pull_request_review_write, mcp__github__add_issue_comment',
  },
  'pr-reviewer': {
    description:
      'Orchestrate comprehensive pull request review using specialized agents for architecture, security, performance, testing, and maintainability. Use PROACTIVELY and AUTOMATICALLY when user wants code reviewed before merge, needs PR feedback, or asks for review of changes. Triggers: "review my changes", "review this PR", "check before merge", "code review", "review the diff", "feedback on changes", "is this ready to merge".',
    dirPath: './pr-reviewer',
    files: ['SKILL.md'],
    allowedTools:
      'Bash(git status:*), Bash(git diff:*), Bash(git branch:*), Bash(git log:*), Bash(git show:*), Task, Read, Grep',
  },
  'prompt-optimizer': {
    description:
      'Optimize AI prompts for better model performance using prompt engineering techniques. Use when user wants to improve a prompt, optimize for better AI responses, reduce token usage, or apply prompt engineering best practices. Triggers: "optimize prompt", "improve prompt", "better prompt", "prompt engineering", "token efficiency", "prompt tuning", "refine prompt", "prompt performance".',
    dirPath: './prompt-optimizer',
    files: ['SKILL.md'],
    allowedTools: 'Read, Write, WebSearch, WebFetch, Task(subagent_type:prompt-engineer)',
  },
  'tech-debt-analyzer': {
    description:
      'Identify, quantify, and prioritize technical debt with actionable remediation plans. Use PROACTIVELY when user mentions technical debt, code quality issues, maintenance challenges, or wants to understand what\'s slowing development. Triggers: "technical debt", "tech debt", "code quality", "maintenance burden", "what\'s slowing us down", "legacy code", "cleanup needed", "code health", "debt analysis".',
    dirPath: './tech-debt-analyzer',
    files: ['SKILL.md'],
    allowedTools: 'Read, Glob, Grep, Bash(git log:*), Bash(git diff:*), Task, WebSearch',
  },
  'topic-researcher': {
    description:
      'Research topics by combining web search with codebase analysis for comprehensive understanding. Use PROACTIVELY and AUTOMATICALLY when user asks about documentation, best practices, how other projects do something, or needs external information combined with codebase context. Triggers: "research", "look up", "find out", "best practices", "how do others", "documentation", "what\'s the", "learn about", "compare with", "check the docs".',
    dirPath: './topic-researcher',
    files: ['SKILL.md'],
    allowedTools:
      'WebSearch, WebFetch, Read, Glob, Grep, Bash(git ls-files:*), Bash(git log:*), Task(subagent_type:researcher)',
  },
} as const;

export type { SkillName };
export const skillNames = Object.keys(skills) as SkillName[];
