/**
 * Slack OAuth Setup Wizard
 *
 * Interactive setup for Slack OAuth credentials when they don't exist.
 * Creates ~/.config/claude-code/slack-env.sh with proper permissions.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import * as readline from 'readline';
import { displayInfo, displaySuccess, displayWarning, colorize } from './display';

const SLACK_ENV_DIR = path.join(os.homedir(), '.config', 'claude-code');
const SLACK_ENV_PATH = path.join(SLACK_ENV_DIR, 'slack-env.sh');

interface SlackCredentials {
  refreshToken: string;
  refreshUrl: string;
}

/**
 * Create a readline interface for user input
 */
function createReadlineInterface(): readline.Interface {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

/**
 * Prompt for a single value with optional masking hint
 */
function prompt(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

/**
 * Prompt for yes/no confirmation
 */
async function confirm(rl: readline.Interface, question: string): Promise<boolean> {
  const answer = await prompt(rl, `${question} (y/n): `);
  return answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes';
}

// OAuth backend URL for obtaining tokens
const OAUTH_BACKEND_URL = 'https://ai-toolkit-slack-oauth-backend.vercel.app';

/**
 * Display setup instructions for obtaining Slack OAuth credentials
 */
function displaySetupInstructions(): void {
  console.log('');
  displayInfo('╔══════════════════════════════════════════════════════════════════╗');
  displayInfo('║              Slack OAuth Setup Wizard                            ║');
  displayInfo('╚══════════════════════════════════════════════════════════════════╝');
  console.log('');
  console.log('To use the Slack integration, you need a refresh token and backend URL.');
  console.log('');
  console.log(colorize('📋 Step-by-Step Instructions:', 'cyan'));
  console.log('');
  console.log(colorize('  Step 1: Visit the OAuth Setup Page', 'yellow'));
  console.log(`    • Open: ${colorize(OAUTH_BACKEND_URL, 'green')}`);
  console.log('    • Click "Add to Slack" and authorize the app');
  console.log('');
  console.log(colorize('  Step 2: Copy Your Tokens', 'yellow'));
  console.log("    • After authorization, you'll see your tokens displayed");
  console.log('    • Copy the Access Token (OAuth Token) - starts with xoxp-...');
  console.log('    • Copy the Refresh Token - starts with xoxe-1-...');
  console.log('');
  console.log(colorize('  Step 3: Enter Your Configuration Below', 'yellow'));
  console.log(`    • Backend Refresh URL: ${colorize(OAUTH_BACKEND_URL, 'green')}`);
  console.log('    • Refresh Token: The xoxe-1-... token you copied');
  console.log('');
}

/**
 * Prompt user for Slack OAuth credentials
 */
async function promptForCredentials(rl: readline.Interface): Promise<SlackCredentials | null> {
  console.log(colorize('Enter your Slack OAuth configuration:', 'cyan'));
  console.log(colorize('(These will be stored in ~/.config/claude-code/slack-env.sh)', 'gray'));
  console.log('');

  console.log(
    colorize(`  SLACK_REFRESH_URL (press Enter for default: ${OAUTH_BACKEND_URL}):`, 'gray')
  );
  const refreshUrlInput = await prompt(rl, '  SLACK_REFRESH_URL: ');
  const refreshUrl = refreshUrlInput || OAUTH_BACKEND_URL;
  console.log(colorize(`  → Using: ${refreshUrl}`, 'green'));
  console.log('');

  const refreshToken = await prompt(rl, '  SLACK_REFRESH_TOKEN: ');
  if (!refreshToken) {
    displayWarning('Refresh Token is required. Aborting setup.');
    return null;
  }

  return { refreshToken, refreshUrl };
}

/**
 * Create the slack-env.sh configuration file
 */
function createSlackEnvFile(credentials: SlackCredentials): void {
  // Ensure directory exists
  if (!fs.existsSync(SLACK_ENV_DIR)) {
    fs.mkdirSync(SLACK_ENV_DIR, { recursive: true, mode: 0o700 });
  }

  // Create file content
  const content = `#!/bin/bash
# Slack OAuth Configuration for claude-plus
# Generated by the @uniswap/ai-toolkit claude-plus setup wizard
#
# SECURITY NOTE: This file contains sensitive credentials.
# Ensure it has restricted permissions (chmod 600).
#
# To use: source this file before running claude-plus
#   source ~/.config/claude-code/slack-env.sh && claude-plus
#
# Or set these as environment variables in your shell profile.

export SLACK_REFRESH_URL="${credentials.refreshUrl}"
export SLACK_REFRESH_TOKEN="${credentials.refreshToken}"
`;

  // Write file with restricted permissions
  fs.writeFileSync(SLACK_ENV_PATH, content, { mode: 0o600 });
}

/**
 * Check if slack-env.sh exists and offer to update it
 */
export function slackEnvExists(): boolean {
  return fs.existsSync(SLACK_ENV_PATH);
}

/**
 * Main setup wizard entry point
 * Returns true if setup was completed, false if skipped/cancelled
 */
export async function runSlackSetupWizard(_verbose?: boolean): Promise<boolean> {
  const rl = createReadlineInterface();

  try {
    // Check if file already exists
    if (slackEnvExists()) {
      console.log('');
      displayInfo(`Slack config already exists at: ${SLACK_ENV_PATH}`);
      const shouldOverwrite = await confirm(
        rl,
        'Do you want to overwrite it with new credentials?'
      );

      if (!shouldOverwrite) {
        displayInfo('Keeping existing configuration.');
        return false;
      }
    }

    // Display instructions
    displaySetupInstructions();

    // Ask if user wants to proceed
    const shouldProceed = await confirm(rl, 'Do you have your Slack OAuth credentials ready?');

    if (!shouldProceed) {
      console.log('');
      displayInfo('Setup skipped. You can run this setup later by running:');
      console.log('  npx @uniswap/ai-toolkit-nx-claude:claude-plus --setup-slack');
      console.log('');
      displayInfo('Or manually create ~/.config/claude-code/slack-env.sh with:');
      console.log('  export SLACK_REFRESH_URL="https://your-backend-url.com"');
      console.log('  export SLACK_REFRESH_TOKEN="your_refresh_token"');
      console.log('');
      return false;
    }

    // Prompt for credentials
    console.log('');
    const credentials = await promptForCredentials(rl);

    if (!credentials) {
      return false;
    }

    // Create the file
    createSlackEnvFile(credentials);

    console.log('');
    displaySuccess(`Slack configuration saved to: ${SLACK_ENV_PATH}`);
    displaySuccess('File permissions set to 600 (owner read/write only)');
    console.log('');
    displayInfo('The credentials will be loaded automatically on next run.');
    displayInfo('You can also source the file manually:');
    console.log(`  source ${SLACK_ENV_PATH}`);
    console.log('');

    return true;
  } finally {
    rl.close();
  }
}

/**
 * Offer setup when Slack config is missing
 * Returns true if user completed setup, false otherwise
 */
export async function offerSlackSetup(verbose?: boolean): Promise<boolean> {
  const rl = createReadlineInterface();

  try {
    console.log('');
    displayWarning('Slack OAuth configuration not found.');
    console.log('');

    const shouldSetup = await confirm(rl, 'Would you like to set up Slack integration now?');
    rl.close();

    if (shouldSetup) {
      return await runSlackSetupWizard(verbose);
    }

    console.log('');
    displayInfo('Skipping Slack setup. Token validation will be skipped.');
    displayInfo(
      'To set up later, run: npx @uniswap/ai-toolkit-nx-claude:claude-plus --setup-slack'
    );
    console.log('');
    return false;
  } catch {
    rl.close();
    return false;
  }
}
